name: learnify
description: "Learnify - Academic Vector Registry"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase Services for Auth and Progress Tracking
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  
  # Networking for Live Google API
  http: ^1.1.0
  webview_flutter: ^4.13.1
  flutter_widget_from_html: ^0.17.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

# APP ICON CONFIGURATION
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#5D5FEF"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true

  # ASSETS CONFIGURATION
  # courses.json has been removed as we are now using the Live API
  assets:
    - assets/app_icon.png